### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework4G2#1]
I found this. Hope it is helpful.

If you find any other useful resource please post it here

You can learn more about developing GitHub Actions tasks in the GitHub Actions documentation: https://docs.github.com/en/actions

**Comment by s4il3sh** [comment]
> I found this. Hope it is helpful.
> 
> If you find any other useful resource please post it here
> 
> You can learn more about developing GitHub Actions tasks in the GitHub Actions documentation: https://docs.github.com/en/actions

Thanks for the info.
