### ISSUE TITLE
To create dirctory

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G2#10]
Do we need to create the directory ".github/workflows/filename.yml" to the main repository or to own repository?

**Comment by s4il3sh** [comment]
I think first you create on your own repo and send a merge request to the main repo.

**Comment by uarif** [comment]
> Do we need to create the directory ".github/workflows/filename.yml" to the main repository or to own repository?

You can create in your own forked one, and then pull a request.
