### ISSUE TITLE
Create separate repository for linting and unit testing.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework4G2#13]
@JustinJaniszewski @s4il3sh we need to create a separate repository for linting and unit testing. Can any one of you do that?

**Comment by s4il3sh** [comment]
@Pranjal-Srivastava-2023 you mean directory?

**Comment by s4il3sh** [comment]
@Pranjal-Srivastava-2023 i don't think we are allowed to create repository.
