### ISSUE TITLE
Ideas for creating new Labels.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework4G2#16]
@s4il3sh @JustinJaniszewski Please suggest some new labels we should add, we need 10. I will create those.

**Comment by s4il3sh** [comment]
Yes of course. Add labels like:
- high priority
- milestone
- brainstorming
- group discussion

**Comment by JustinJaniszewski** [comment]
maybe also "algorithm" and "unit testing" since there is already a default one for documentation

**Comment by JustinJaniszewski** [comment]
Another group has a "suggestion" label. We could use that too

**Comment by reshnashrestha** [comment]
I liked the high priority label here.

**Comment by s4il3sh** [comment]
@Pranjal-Srivastava-2023 I am expecting that you will add those labels. So far only four labels added. We need six more guys.

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh we have 10 labels.
