### ISSUE TITLE
Task completion

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework4G2#19]
What is task completion in the HW (Interaction with other groups)?

**Comment by Pranjal-Srivastava-2023** [comment]
@uarif I thought task completion was a separate set of points, independent from (Interaction with other groups). 5 points are awarded for completing the HW task (in this case unit testing and linting). Am I wrong?

**Comment by reshnashrestha** [comment]
Yeah, the task completion has 5 points.

**Comment by s4il3sh** [comment]
> @uarif I thought task completion was a separate set of points, independent from (Interaction with other groups). 5 points are awarded for completing the HW task (in this case unit testing and linting). Am I wrong?

I guess that's it!
