### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework4G2#2]
we should discuss who will be the maintainer. Has anyone not been maintainer or does anyone one prefer being the maintainer?

**Comment by s4il3sh** [comment]
I am okay with anyone being a maintainer. I have been a maintainer once.

**Comment by JustinJaniszewski** [comment]
I have also been a maintainer once. Pranjal I think you could be maintainer if you would prefer that.

**Comment by s4il3sh** [comment]
is this issue fixed? Who is the maintainer?

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh Yes, it is fixed. I am the maintainer.
