### ISSUE TITLE
Your code has been rated at 7.27/10

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework4G2#43]
@s4il3sh I used your code from HW3 and after some modifications performed unit-test and linting using GitHub Actions. The code now passes the unit-test but the linting score can be improved. Can you go over the code and fix the issues so that we get 10/10?

**Comment by reshnashrestha** [comment]
@Pranjal-Srivastava-2023 Can you elaborate the process you followed for this ?

**Comment by s4il3sh** [comment]
> @s4il3sh I used your code from HW3 and after some modifications performed unit-test and linting using GitHub Actions. The code now passes the unit-test but the linting score can be improved. Can you go over the code and fix the issues so that we get 10/10?

@Pranjal-Srivastava-2023 Sure I can do that. Thanks for pointing it out. By the way, is the unit-test working?

**Comment by s4il3sh** [comment]
@Pranjal-Srivastava-2023 finally worked it out. The code is 10/10. Please accept merge request.

**Comment by Pranjal-Srivastava-2023** [comment]
> @Pranjal-Srivastava-2023 Can you elaborate the process you followed for this ?

@reshnashrestha we used pylint, it rates the code. You can look at our linting file in the workflow.

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh it's 10/10 now. Thanks!
