### ISSUE TITLE
Unit testing and linting for HW3 solutions

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework4G2#44]
@Pranjal-Srivastava-2023 Use .yml files to perform unit testing and linting in .github/workflow.

**Comment by reshnashrestha** [comment]
@Pranjal-Srivastava-2023 have you carried on linting, pytest?

**Comment by s4il3sh** [comment]
> @Pranjal-Srivastava-2023 have you carried on linting, pytest?

Yes. We did!
