### ISSUE TITLE
Change milestone

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework4G2#46]
I don't think a milestone should be the entire homework. Maybe try milestones such as "Documentation", "Algorithm", and "Unit Test" instead.

**Comment by reshnashrestha** [comment]
Yeah, milestone can be on entire homework as well as on other task completions.

**Comment by s4il3sh** [comment]
> I don't think a milestone should be the entire homework. Maybe try milestones such as "Documentation", "Algorithm", and "Unit Test" instead.

Agreed!

**Comment by Pranjal-Srivastava-2023** [comment]
@JustinJaniszewski @s4il3sh HW4 is only the title of the milestone. Inside it, we have issues related to algorithms, documentation, and unit testing. It's not a problem.
