### ISSUE TITLE
Documentation help

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework4G2#47]
Any tips on what I should document or is there anything you'd like to see included?

**Comment by reshnashrestha** [comment]
A friendly suggestion, you can add the pytest result and describe on it on the documentation

**Comment by s4il3sh** [comment]
Yep. You can add the output of linting too. Showing the quality of our code and also you may add the screenshot of github action.

**Comment by tirthbha** [comment]
@JustinJaniszewski For the documentation part, as mentioned in the content of our HW, we need to explain about github action implementation, make a list of changes that we have made to our previous HW (2 or 3)  for the unit test and algorithm, and of-course as mentioned by @reshnashrestha and @s4il3sh adding results of pytest and linting to the documentation will make it more worth.

**Comment by JustinJaniszewski** [comment]
Thanks everybody for your help.
