### ISSUE TITLE
Output for pytest and linting

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G2#48]
How could we get the output for the pytest and linting using github action?

**Comment by s4il3sh** [comment]
You may check this code for linting:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you want to use

    - name: Install linter
      run: pip install pylint

    - name: Lint spring_constant_unittest.py
      run: pylint spring_constant_unittest.py

in place of ''spring_constant_unitttest.py" you can add your file.

**Comment by tirthbha** [comment]
@s4il3sh I got it. But Im using flake8, while I'm running the code it shows error that we need to sort out. Do you know how to remove those error?

**Comment by tirthbha** [comment]
Thank you for your response.
