### ISSUE TITLE
let's decide homework

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework4G2#5]
We all are from different groups previously. So, which homework are we going to choose for our work? Let's decide.

**Comment by JustinJaniszewski** [comment]
I believe me and you @s4il3sh worked together on the last homework. So, I suggest we do that one (HW3). We would both understand what is going on and we would both be able to answer @Pranjal-Srivastava-2023 's questions if he has any.

**Comment by reshnashrestha** [comment]
What was your previous homework solution? which classical function? was it the spring constant one?

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh @JustinJaniszewski which classical function did you choose last homework?

**Comment by JustinJaniszewski** [comment]
We chose spring constant

**Comment by JustinJaniszewski** [comment]
Do we have 4 members in our group?

**Comment by s4il3sh** [comment]
> Do we have 4 members in our group?

No, we are 3.
