### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G2#50]
Hi guys, I am confused on :
If we are using both pylint and flake8?
any details on this will be appreciated.

**Comment by s4il3sh** [comment]
According to the homework prof. mentioned using lint but flake8 does the same work, right? So, I guess anyone should work to improve the quality of the code.

**Comment by tirthbha** [comment]
@reshnashrestha I think, pylint will be the better option, as I have faced unresolved issues with the flaked. However, pylint made our task easier.

**Comment by reshnashrestha** [comment]
@tirthbha @s4il3sh  thank you for response. 
I have used pylint to modify and finally got 10/10.
