### ISSUE TITLE
What to Include in Changelog Documentation?

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework4G2#61]
What should we be including in the changelog for the documentation? I'm concerned that we won't have too much to change so my changelog section of the documentation may be lacking. Has your group been having this issue?

**Comment by tirthbha** [comment]
Are we going to use any tool to get changelog for the documentation or something else? I am also confused about this section.

**Comment by JustinJaniszewski** [comment]
from my current understanding, look at what your other group members did, see what code had to be added or changed in order for the github action implementation to work.

**Comment by tirthbha** [comment]
@JustinJaniszewski You mean we should do that by manually?

**Comment by JustinJaniszewski** [comment]
I believe so, yes.

**Comment by JustinJaniszewski** [comment]
I am closing this issue. Refer to the comments on #76. If you are still confused, feel free to reopen this.
