### ISSUE TITLE
How to create separate module/function for unit test?

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G2#70]
Any ideas will be appreciated.

**Comment by tirthbha** [comment]
@reshnashrestha You can create a module file just as you created in the previous homework for example, create a module named **module_file.py** based on your code. Then create a separate file for tests, say **test_file.py**, which imports your created module. Finally, add the **module_file.py** and **test_file.py** to your repository.

**Comment by reshnashrestha** [comment]
@tirthbha Thank you. It appeared that I did this way earlier. I was just confused with the words. 
Can you please check out my work?
[projectile_unit_test.py](https://github.com/ubsuny/23-Homework4G1/blob/main/projectile_unit_test.py)
