### ISSUE TITLE
where can I find the output of the linting?

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework4G2#73]
I want to include this in my documentation but I do not see it.

**Comment by Pranjal-Srivastava-2023** [comment]
We have not generated the output files as it was not part of the homework but you can find details, such as code scores in the repository. Just click on the green checkmark.

![image](https://github.com/ubsuny/23-Homework4G2/assets/143828394/9dd6c582-f899-4aa6-b217-48a1593f2a95)

**Comment by JustinJaniszewski** [comment]
Thank you so much thats very helpful
