### ISSUE TITLE
What did you have to change in the original code

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework4G2#74]
What did you have to change in the original code to make it work with github actions?

**Comment by Pranjal-Srivastava-2023** [comment]
@JustinJaniszewski while running the unit test using GitHubActions the major problem was a discrepancy between the calculated and expected value of k. I fixed line:
avg = np.average([val for val in spring_constants if val is not None]) * 10 ** (-2)
Specifically changed 10**(-3) to 10**(-2).

**Comment by JustinJaniszewski** [comment]
Got it. Thanks for the help!
