### ISSUE TITLE
Finishing documentation

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework4G2#76]
After my pull request gets accepted I think I am pretty much finished with the documentation. If theres any concerns, mistakes, or things you would like to see added feel free to let me know with a comment under this issue or in a new issue. Thank you.

**Comment by tirthbha** [comment]
@JustinJaniszewski How did you create changelog for the documentation?

**Comment by JustinJaniszewski** [comment]
So, I looked at the errors that popped up during github actions (linting and unit test). Then, I looked at the merge requests made afterwards that assured that the tests passed. What my group members changed in those merge requests, I included in the changelog.

**Comment by JustinJaniszewski** [comment]
No problem, let me know if you need anything else.
