### ISSUE TITLE
Missing Milestone

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework4G2#77]
Hey @Pranjal-Srivastava-2023 I don't want to keep bothering you about it but we still only have 1 milestone and the due date is approaching. We have created multiple issues about it but I still only see 1 milestone. You could check out #65 and #46 for some ideas or make your own, we only need one more.

**Comment by Pranjal-Srivastava-2023** [comment]
@JustinJaniszewski it is created. Please close the issue when the task is completed. That's the point of creating milestones so that we can track the progress.
