### ISSUE TITLE
Task distribution G2.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework4G2#9]
@JustinJaniszewski @s4il3sh let's discuss task distribution. Who is doing what?

**Comment by JustinJaniszewski** [comment]
I wouldn't mind doing unit tests or the algorithm. Which task would you prefer?

**Comment by s4il3sh** [comment]
I haven't tried unit test yet.

**Comment by JustinJaniszewski** [comment]
you can do unit test then if you want. I dont really mind any role. I haven't tried documentation yet though.

**Comment by Pranjal-Srivastava-2023** [comment]
@JustinJaniszewski you can do the documentation this time then, if you want.

**Comment by JustinJaniszewski** [comment]
Alright, I'll try it.

**Comment by s4il3sh** [comment]
Great! Let's finalize -
Maintainer --  ?
documentation -- @JustinJaniszewski 
unittest -- @s4il3sh 
GitHub action -- ?

I guess the algorithm is github action this time.

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh Final!

Maintainer -- @Pranjal-Srivastava-2023 
documentation -- @JustinJaniszewski
unittest -- @s4il3sh
GitHub action -- @Pranjal-Srivastava-2023

**Comment by s4il3sh** [comment]
Ok. Cool!

**Comment by JustinJaniszewski** [comment]
sounds good to me
